# -*- coding: utf-8 -*-
"""Chat_with_CSV_&_Excel_using_LangChain_and_OpenAI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134B6qsMcFWhfiBmhyyfErh6WPqkIr3dk
"""

!pip install -q langchain openai chromadb

from langchain.document_loaders import CSVLoader
from langchain.indexes import VectorstoreIndexCreator
from langchain.chains import RetrievalQA
from langchain.llms import OpenAI
import os

os.environ["OPENAI_API_KEY"] = "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"

# Load the documents
loader = CSVLoader(file_path='/content/ctg-studies (2).csv')

pip install tiktoken

# Create an index using the loaded documents
index_creator = VectorstoreIndexCreator()
docsearch = index_creator.from_loaders([loader])

# Create a question-answering chain using the index
chain = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", retriever=docsearch.vectorstore.as_retriever(), input_key="question")

# Pass a query to the chain
query = "Do you have a column called Interventions and can you provide Drugs name used in this column for each 100 rows in one column named as Drugs?"
response = chain({"question": query})

print(response['result'])

